lib/task_tracker_web/router.ex
defmodule TaskTrackerWeb.Router do
  use TaskTrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TaskTrackerWeb.Plugs.FetchSession
  end

  pipeline :ajax do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash
    plug TaskTrackerWeb.Plugs.FetchSession # FIXME: "FetchUser"
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TaskTrackerWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/users", UserController
    resources "/tasks", TaskController
    resources "/sessions", SessionController, only: [:create, :delete], singleton: true
  end

  scope "/ajax", TaskTrackerWeb do
    pipe_through :ajax
    resources "/times", TaskTimeController
  end

  # Other scopes may use custom stacks.
  # scope "/api", TaskTrackerWeb do
  #   pipe_through :api
  # end
end

lib/task_tracker_web/views/layout_view.ex
defmodule TaskTrackerWeb.LayoutView do
  use TaskTrackerWeb, :view
end

lib/task_tracker_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>TaskTracker</title>
    <link rel="stylesheet" href="<%= Routes.static_url(@conn, "/css/app.css") %>"/>
   </head>
  <body>
    <main role="main" class="container">
        <nav class="p-0 py-1 navbar navbar-expand-md navbar-light">
            <a class="navbar-brand text-primary" href="/tasks" >Task Tracker</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mr-auto">
                  <li class="nav-item p-1">
                    <a class="text-dark" href="/">Registration</a>
                  </li>
                  <li class="nav-item p-1">
                    <a class="text-dark" href="/users">Users</a>
                  </li>
                  <li class="nav-item p-1">
                      <a class="text-dark" href="/tasks">Tasks</a>
                  </li>


                    <%= if @current_user do %>
                      <li class="nav-item p-1">
                        User:
                        <%= @current_user.email %>
                        <%= link("Logout", to: Routes.session_path(@conn, :delete),
                          method: :delete) %>
                      </li>
                    <% else %>
                      <li class="nav-item">
                      <%= form_for @conn, Routes.session_path(@conn, :create),
                              [class: "form-inline"], fn f -> %>
                        <%= text_input f, :email, class: "form-control mr-sm-2" %>
                        <%= submit "Login", class: "btn btn-outline-primary my-2 my-sm-0" %>
                      <% end %>
                      </li>
                    <% end %>


                </ul>
            </div>
        </nav>
        <div class="row">
            <div class="col-12">
              <%= if get_flash(@conn, :info) do %>
                <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
              <% end %>
              <%= if get_flash(@conn, :error) do %>
                <p class="alert alert-danger" role="alert">
                  <%= get_flash(@conn, :error) %>
                </p>
              <% end %>
            </div>
        </div>

         <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>